# Generated by Django 3.0.5 on 2020-07-28 13:35

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMsters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=25400)),
                ('imageurl', embed_video.fields.EmbedVideoField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=25500)),
                ('featureimages', models.ImageField(default='', upload_to='')),
                ('description', models.CharField(default='', max_length=25000)),
            ],
        ),
    ]
