# Generated by Django 3.0.5 on 2020-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmsters',
            name='imageurl',
            field=models.CharField(default='', max_length=25400),
        ),
    ]
