# Generated by Django 3.0.5 on 2020-08-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200729_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=25400)),
                ('description', models.CharField(default='', max_length=25000)),
                ('createdon', models.DateTimeField(default='')),
            ],
        ),
    ]
