# Generated by Django 3.0.5 on 2020-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdon',
            field=models.CharField(default='', max_length=500),
        ),
    ]
