# Generated by Django 3.0.5 on 2020-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200805_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdon',
            field=models.CharField(default='', max_length=25400),
        ),
    ]
