# Generated by Django 3.0.5 on 2020-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200805_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=25400)),
                ('photo', models.CharField(default='', max_length=25000)),
                ('mobile', models.CharField(default='', max_length=25400)),
                ('address', models.CharField(default='', max_length=25400)),
            ],
        ),
    ]
