# Generated by Django 3.0.5 on 2020-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
