# Generated by Django 3.0.5 on 2020-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200809_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title',
            field=models.CharField(default='', max_length=25400),
        ),
    ]
