# Generated by Django 3.0.5 on 2020-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_settings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='facebook',
            field=models.CharField(default='', max_length=25400),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.CharField(default='', max_length=25400),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter',
            field=models.CharField(default='', max_length=25400),
        ),
    ]
