# Generated by Django 3.0.5 on 2020-08-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200809_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='createdon',
        ),
    ]
